### PR TITLE
Update igor2 to be supported again

### PR DESCRIPTION
**Pull request by nsulmol**
Igor2 was not supported with SciFiReaders, because our version of numba
requred numpy 1.24.4, while Igor2 required numpy 1.25.1 with release
0.5.3.

However, since numba 0.58.0, numba now supports numpy >= 1.22 (including
1.25)! By updating numba, we are able to install igor2 without conflicts.

Thinking about it, the 'real' issue was that our igor2 version did not
require a strict version. If we set igor2 to the current version (with
these changes), we should minimize the likelihood of this issue propping
up again.

Note, however, that any improvements of igor2 will be lost. A more
'proper' solution would likely be to mix a more general pyproject.toml
with a 'lock' file defining the versions that worked for the developers
of SciFiReaders.

### CODE REVIEW

**Comment by nsulmol** [comment]
Well, the tests keep failing with this:

 **The conflict is caused by:
    The user requested numpy>=1.24
    igor2 0.5.3 depends on numpy>=1.25.1**

Which makes no sense to me. I cannot replicate it on my end. Any clue what is going on?

**Comment by gduscher** [comment]
There is a new version of numba coming out with the release candidate numba==0.59rc1 works  with python 3.12 but there seems to be a problem with python 3.9 and lower. Not sure where the problem lays.

**Comment by nsulmol** [comment]
@gduscher : Thanks for the answer. What should that mean in terms of this PR? Do you want to wait until the numba release candidate is an official release, in hopes that it will resolve issues with Python 3.8? I have tested this PR on Python 3.10.11, for reference, and it works.

Currently, igor2 cannot be installed in the SciFiReaders virtual environment because of the above.

Thanks,
Nick

**Comment by ramav87** [comment]
One way to proceed would be for us to remove python 3.8 support then accept the PR for now, and then revisit it once there is a new numba release that is official. @gduscher thoughts?

**Comment by ramav87** [comment]
@nsulmol it does seem that things are working now on the latest commit:

https://github.com/pycroscopy/SciFiReaders/actions/runs/7588693030

Can you try with the latest on main, to check?

**Comment by nsulmol** [comment]
@ramav87 : I can confirm that the latest main on pycroscopy works, so this PR is not necessary. Thank you for the support.

As an aside: please note that your extras_require.txt and the dependencies in setup.py do not match anymore (e.g., a specific numpy version is still mentioned in extras_require.txt). Perhaps that is intentional, but I figured I'd mention.

I will close this, thanks again.
- Nick

**Pull request closed without merging**
